## Holiday Package Prediciton

### 1) Problem statement.
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base.
One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information.
The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.
However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.
### 2) Data Collection.
The Dataset is collected from https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction
The data consists of 20 column and 4888 rows.

In [15]:
import warnings

In [16]:
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

In [17]:
from Configurations.imports import *

In [18]:
# import the base
from Configurations.file_path import data_parent_path, base
file = data_parent_path / "travel.csv"

In [19]:
# read the data
df = pd.read_csv(file)
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

#### Data Cleaning

In [20]:
# Understanding the data
print(df.shape)

# checking the data type
df.info()

(4888, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [21]:
# checking the duplicate rows
df.duplicated().sum()

np.int64(0)

In [22]:
# checking for the duplicate columns
df.T.duplicated().sum()

np.int64(0)

In [23]:
# handling the missing values
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [24]:
# handling the column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
df

,customerid,prodtaken,age,typeofcontact,citytier,durationofpitch,occupation,gender,numberofpersonvisiting,numberoffollowups,productpitched,preferredpropertystar,maritalstatus,numberoftrips,passport,pitchsatisfactionscore,owncar,numberofchildrenvisiting,designation,monthlyincome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [25]:
# filling the missing values

#age
df["age"] = df["age"].fillna(df["age"].median())

#type of contact
df["typeofcontact"] = df["typeofcontact"].astype("category").fillna(df["typeofcontact"].mode())

#duration of the pitch
df["durationofpitch"] = df["durationofpitch"].fillna(df["durationofpitch"].mean())

# number of follow ups
df["numberoffollowups"] = df["numberoffollowups"].fillna(df["numberoffollowups"].mean())

# prefered property star
df["preferredpropertystar"] = df["preferredpropertystar"].dropna()

#number of the trips
df["numberoftrips"] = df["numberoftrips"].fillna(df["numberoftrips"].mean())

#number of children visiting 
df["numberofchildrenvisiting"] = df["numberofchildrenvisiting"].fillna(df["numberofchildrenvisiting"].mean())

# monthly income
df["monthlyincome"] = df["monthlyincome"].fillna(df["monthlyincome"].mean())

In [26]:
# remove the remaining the missing values
df = df.dropna()
df.isna().sum()

customerid                  0
prodtaken                   0
age                         0
typeofcontact               0
citytier                    0
durationofpitch             0
occupation                  0
gender                      0
numberofpersonvisiting      0
numberoffollowups           0
productpitched              0
preferredpropertystar       0
maritalstatus               0
numberoftrips               0
passport                    0
pitchsatisfactionscore      0
owncar                      0
numberofchildrenvisiting    0
designation                 0
monthlyincome               0
dtype: int64

In [27]:
# handling the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4837 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customerid                4837 non-null   int64
 1   prodtaken                 4837 non-null   int64
 2   age                       4837 non-null   float64
 3   typeofcontact             4837 non-null   category
 4   citytier                  4837 non-null   int64
 5   durationofpitch           4837 non-null   float64
 6   occupation                4837 non-null   object
 7   gender                    4837 non-null   object
 8   numberofpersonvisiting    4837 non-null   int64
 9   numberoffollowups         4837 non-null   float64
 10  productpitched            4837 non-null   object
 11  preferredpropertystar     4837 non-null   float64
 12  maritalstatus             4837 non-null   object
 13  numberoftrips             4837 non-null   float64
 14  passport                  4837 non-null   int64
 15  pitchsatisfactionscore    4837 non-null   int64
 16  owncar                    4837 non-null   int64
 17  numberofchildrenvisiting  4837 non-null   float64
 18  designation               4837 non-null   object
 19  monthlyincome             4837 non-null   float64
dtypes: category(1), float64(7), int64(7), object(5)
memory usage: 760.6+ KB

In [28]:
# handling the categorical
def convertToCategory():
    cols = ["occupation","gender","productpitched","maritalstatus","designation"]
    
    for col in cols:
        df[col] = df[col].astype("category")

convertToCategory()

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4837 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customerid                4837 non-null   int64
 1   prodtaken                 4837 non-null   int64
 2   age                       4837 non-null   float64
 3   typeofcontact             4837 non-null   category
 4   citytier                  4837 non-null   int64
 5   durationofpitch           4837 non-null   float64
 6   occupation                4837 non-null   category
 7   gender                    4837 non-null   category
 8   numberofpersonvisiting    4837 non-null   int64
 9   numberoffollowups         4837 non-null   float64
 10  productpitched            4837 non-null   category
 11  preferredpropertystar     4837 non-null   float64
 12  maritalstatus             4837 non-null   category
 13  numberoftrips             4837 non-null   float64
 14  passport                  4837 non-null   int64
 15  pitchsatisfactionscore    4837 non-null   int64
 16  owncar                    4837 non-null   int64
 17  numberofchildrenvisiting  4837 non-null   float64
 18  designation               4837 non-null   category
 19  monthlyincome             4837 non-null   float64
dtypes: category(6), float64(7), int64(7)
memory usage: 596.2 KB

In [30]:
# handling the extreme values and outliers
df["gender"] = df["gender"].str.replace("Fe Male","Female")
df["maritalstatus"] = df["maritalstatus"].str.replace("Single","Unmarried")

In [31]:
# Remove the unwanted column
df.drop("customerid", axis=1, inplace=True)

#### Feature Extraction

In [32]:
# total visiting
df["totalvising"] = df["numberofchildrenvisiting"] + df["numberofpersonvisiting"]
df.drop(columns=["numberofchildrenvisiting","numberofpersonvisiting"], axis=1, inplace=True)

In [33]:
def feature_types(df):

    # numerical features
    numerical_features = df.select_dtypes(
        include=['int64', 'float64']
    ).columns

    # categorical features
    categorical_features = df.select_dtypes(
        include=['object', 'category']
    ).columns

    # discrete features (numerical with small unique values)
    discrete_features = [
        col for col in numerical_features
        if df[col].nunique() < 25
    ]

    # continuous features (numerical but not discrete)
    continuous_features = [
        col for col in numerical_features
        if col not in discrete_features
    ]

    print("Numerical Features:", len(numerical_features))
    print("Categorical Features:", len(categorical_features))
    print("Discrete Features:", len(discrete_features))
    print("Continuous Features:", len(continuous_features))

    return numerical_features, categorical_features, \
           discrete_features, discrete_features
           
res = feature_types(df)

Numerical Features: 12
Categorical Features: 6
Discrete Features: 9
Continuous Features: 3

In [34]:
numerical_features,categorical_features,discrete_features,discrete_features = res

#### Test and Train split of the dataset

In [35]:
# independent and dependent features
X = df.drop("prodtaken", axis=1) # independent feature

In [36]:
y = df["prodtaken"]

In [37]:
#test and train split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=24)
x_train.shape, x_test.shape

((3869, 17), (968, 17))

In [38]:
numerical_features = [col for col in numerical_features if col != "prodtaken"]
numerical_features

['age',
 'citytier',
 'durationofpitch',
 'numberoffollowups',
 'preferredpropertystar',
 'numberoftrips',
 'passport',
 'pitchsatisfactionscore',
 'owncar',
 'monthlyincome',
 'totalvising']

#### Encoding

In [39]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

oh_transformer = OneHotEncoder(drop="first")
num_transformer = StandardScaler()

preprocessor = ColumnTransformer([
    ("OneHotEncoder", oh_transformer, categorical_features),
    ("StandardScaler", num_transformer, numerical_features)
])

In [40]:
x_train = preprocessor.fit_transform(x_train)

In [41]:
x_test = preprocessor.transform(x_test)

#### Training

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

In [45]:
model = RandomForestClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [46]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9307851239669421
Precision: 0.9302325581395349
Recall: 0.6741573033707865
F1 Score: 0.7817589576547231
ROC AUC Score: 0.8313824491537477

Confusion Matrix:
[[781   9]
 [ 58 120]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       790
           1       0.93      0.67      0.78       178

    accuracy                           0.93       968
   macro avg       0.93      0.83      0.87       968
weighted avg       0.93      0.93      0.93       968

In [48]:
y_prob = model.predict_proba(x_test)[:,1]
roc_auc_score(y_test, y_prob)

0.9683402076518277

#### Hyper Parameter tuning

n_estimators: Int = 100,
    *,
    criterion: Literal['gini', 'entropy', 'log_loss'] = "gini",
    max_depth: Int | None = None,
    min_samples_split: float = 2,
    min_samples_leaf: float = 1,
    min_weight_fraction_leaf: Float = 0,
    max_features: float | Literal['sqrt', 'log2'] = "sqrt",
    max_leaf_nodes: Int | None = None,

In [49]:
rf_params = {
    "n_estimators":[100,250,500,1000],
    "max_depth":[3,5,7,10],
    "min_samples_split":[5,10,20],
    "max_features":['sqrt', 'log2']
}

In [50]:
from sklearn.model_selection import GridSearchCV
search = GridSearchCV(estimator=model, param_grid=rf_params, cv=5, scoring="accuracy",refit=True,verbose=True,n_jobs=-1)

In [51]:
search.fit(x_train,y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 10],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_split': [5, 10, 20],
                         'n_estimators': [100, 250, 500, 1000]},
             scoring='accuracy', verbose=True)

In [56]:
y_pred = search.predict(x_test)

In [57]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8842975206611571
Precision: 0.875
Recall: 0.43258426966292135
F1 Score: 0.5789473684210527
ROC AUC Score: 0.7093301095150051

Confusion Matrix:
[[779  11]
 [101  77]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.99      0.93       790
           1       0.88      0.43      0.58       178

    accuracy                           0.88       968
   macro avg       0.88      0.71      0.76       968
weighted avg       0.88      0.88      0.87       968

In [58]:
y_prob = search.predict_proba(x_test)[:,1]
roc_auc_score(y_test, y_prob)

0.9268596216754372